#!/bin/bash

commands=(
"node bin/hexpass.js"
"node bin/hexpass.js 16"
"node bin/hexpass.js 0"
"node bin/hexpass.js -1"
"node bin/hexpass.js abc"
"node bin/hexpass.js 1025"
"node bin/hexpass.js --bytes 16"
"node bin/hexpass.js --bytes 0"
"node bin/hexpass.js --bytes 513"
"node bin/hexpass.js --bytes abc"
"node bin/hexpass.js --bytes"
"node bin/hexpass.js --bytes 16 --bytes 32"
"node bin/hexpass.js 32 --bytes 16"
"node bin/hexpass.js --count 5"
"node bin/hexpass.js 16 --count 2"
"node bin/hexpass.js --count 0"
"node bin/hexpass.js --count 101"
"node bin/hexpass.js --count"
"node bin/hexpass.js --count 5 --count 10"
"node bin/hexpass.js --env"
"node bin/hexpass.js --env TEST"
"node bin/hexpass.js 16 --env TEST"
"node bin/hexpass.js --env \"\""
"node bin/hexpass.js --env \"with spaces\""
"node bin/hexpass.js --env --count 2"
"node bin/hexpass.js --env TEST --env VAR"
"node bin/hexpass.js --json"
"node bin/hexpass.js 16 --json"
"node bin/hexpass.js --bytes 16 --json"
"node bin/hexpass.js --count 2 --json"
"node bin/hexpass.js --env TEST --json"
"node bin/hexpass.js --json --copy"
"node bin/hexpass.js --copy"
"node bin/hexpass.js --env TEST --copy"
"node bin/hexpass.js --count 2 --copy"
"node bin/hexpass.js --json --copy"
"node bin/hexpass.js --help"
"node bin/hexpass.js -h"
"node bin/hexpass.js --version"
"node bin/hexpass.js -v"
"node bin/hexpass.js --unknown"
"node bin/hexpass.js 32 64"
"node bin/hexpass.js --count 1 --env TEST --json"
"node bin/hexpass.js --bytes 512"
"node bin/hexpass.js 1024"
"node bin/hexpass.js --count 100"
"node bin/hexpass.js 1"
"node bin/hexpass.js --bytes 1"
)

for cmd in "${commands[@]}"; do
    echo "Command: $cmd"
    eval "$cmd" 2>&1
    echo "Exit code: $?"
    echo "-----"
done